apiVersion: v1
kind: Service
metadata:
  labels:
    name: data-monitoring
  name: data-monitoring
  namespace: gridvo
spec:
  selector:
    name: data-monitoring
  ports:
     - port: 80
       targetPort: 3001
